src/Entity/Brand.php
<?php

namespace App\Entity;

use App\Repository\BrandRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrandRepository::class)]
class Brand
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $article_number = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    /**
     * Заполнение полей сущности по строчке csv/xls/xlsx таблицы
     * @param array $spreadsheetIndexes
     * @param array $spreadsheetLine
     */
    public function fillBySpreadsheetLine(array $spreadsheetIndexes, array $spreadsheetLine)
    {
        foreach ($spreadsheetIndexes as $indexName => $index) {
            $this->$indexName = trim($spreadsheetLine[$index]);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getArticleNumber(): ?string
    {
        return $this->article_number;
    }

    public function setArticleNumber(string $article_number): self
    {
        $this->article_number = $article_number;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $brand = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $article_number = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?float $total_balance = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $measurement_unit = null;

    #[ORM\Column(nullable: true)]
    private ?float $additional_price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_link = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $technical_description = null;

    #[ORM\Column(nullable: true)]
    private ?int $used = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $additional_images_links = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $auto_model = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $auto_brand = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category = null;

    #[ORM\Column(nullable: true)]
    private ?float $length = null;

    #[ORM\Column(nullable: true)]
    private ?float $width = null;

    #[ORM\Column(nullable: true)]
    private ?float $height = null;

    #[ORM\Column(nullable: true)]
    private ?float $weight = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getArticleNumber(): ?string
    {
        return $this->article_number;
    }

    public function setArticleNumber(?string $article_number): self
    {
        $this->article_number = $article_number;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getTotalBalance(): ?float
    {
        return $this->total_balance;
    }

    public function setTotalBalance(?float $total_balance): self
    {
        $this->total_balance = $total_balance;

        return $this;
    }

    public function getMeasurementUnit(): ?string
    {
        return $this->measurement_unit;
    }

    public function setMeasurementUnit(?string $measurement_unit): self
    {
        $this->measurement_unit = $measurement_unit;

        return $this;
    }

    public function getAdditionalPrice(): ?float
    {
        return $this->additional_price;
    }

    public function setAdditionalPrice(?float $additional_price): self
    {
        $this->additional_price = $additional_price;

        return $this;
    }

    public function getImageLink(): ?string
    {
        return $this->image_link;
    }

    public function setImageLink(?string $image_link): self
    {
        $this->image_link = $image_link;

        return $this;
    }

    public function getTechnicalDescription(): ?string
    {
        return $this->technical_description;
    }

    public function setTechnicalDescription(?string $technical_description): self
    {
        $this->technical_description = $technical_description;

        return $this;
    }

    public function getUsed(): ?int
    {
        return $this->used;
    }

    public function setUsed(?int $used): self
    {
        $this->used = $used;

        return $this;
    }

    public function increaseTotalBalance(int $quantity = 1)
    {
        $this->total_balance += $quantity;
    }

    public function decreaseTotalBalance(int $quantity = 1)
    {
        if ($this->total_balance >= $quantity)
            $this->total_balance -= $quantity;
    }

    public function getAdditionalImagesLinks(): ?string
    {
        return $this->additional_images_links;
    }

    public function setAdditionalImagesLinks(?string $additional_images_links): self
    {
        $this->additional_images_links = $additional_images_links;

        return $this;
    }

    public function getAutoModel(): ?string
    {
        return $this->auto_model;
    }

    public function setAutoModel(?string $auto_model): self
    {
        $this->auto_model = $auto_model;

        return $this;
    }

    public function getAutoBrand(): ?string
    {
        return $this->auto_brand;
    }

    public function setAutoBrand(?string $auto_brand): self
    {
        $this->auto_brand = $auto_brand;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLength(): ?float
    {
        return $this->length;
    }

    public function setLength(?float $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getWidth(): ?float
    {
        return $this->width;
    }

    public function setWidth(?float $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?float
    {
        return $this->height;
    }

    public function setHeight(?float $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }
}

src/Controller/DetailsController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\BrandRepository;
use App\Repository\ProductRepository;
use App\Service\DataMapping;
use App\Service\ThirdParty\Abcp\AbcpApi;
use GuayaquilLib\ServiceOem;
use JMS\Serializer\SerializerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/details')]
class DetailsController extends AbstractController
{
    private ServiceOem $serviceOem;

    public function __construct()
    {
        $this->serviceOem = new ServiceOem($_ENV['OEM_LOGIN'], $_ENV['OEM_PASSWORD']);
    }

    /**
     * Отдельная страница с информацией об определённом товаре
     */
    #[Route('/item/{id}', name: 'detail_page')]
    #[IsGranted('ROLE_USER')]
    public function show($id, ProductRepository $productRep): Response
    {
        /** @var User $user */
        $user = $this->getUser(); # todo
        $cartItems = $user->getCart()->getItems();
        $inCartQuantity = 0;
        foreach ($cartItems as $cartItem) {
            if ($cartItem->getProduct()->getId() === $id) {
                $inCartQuantity = $cartItem->getQuantity();
            }
        }

        $product = $productRep->find($id);
        return $this->render('details/detail_page.html.twig', [
            'product' => $product,
            'in_cart_quantity' => $inCartQuantity
        ]);
    }

    /**
     * Кусок html-блока с информацией о товаре
     */
    #[Route('/{articleNumber}', name: 'detail_info')]
    public function info($articleNumber, Request $request, AbcpApi $abcpApi): Response
    {
        $foundArticle = $abcpApi->searchProcessor->getConcreteArticleByItemKeyAndNumber($request->query->get('itemKey'), $articleNumber);

        return $this->render('details/detail_info.html.twig', [
            'product' => $foundArticle,
            'descriptionArrayIndexes' => (new DataMapping())->getData('position_description_array_indexes')
        ]);
    }

    #[Route('/ajax/brands', name: 'detail_brands')]
    public function brands(BrandRepository $brandRep, SerializerInterface $serializer): JsonResponse
    {
        $brands = json_decode($serializer->serialize($brandRep->findAll(), 'json'), true);

        $uniqueBrands = [];
        array_filter($brands, function ($item) use (&$uniqueBrands) {
            if (!in_array(['brand' => $item['brand']], $uniqueBrands)) {
                $uniqueBrands[] = ['brand' => $item['brand']];
                return true;
            }
            return false;
        });

        return (new JsonResponse($uniqueBrands));
    }

    #[Route('/ajax/brand_models/{brand}', name: 'detail_brand_models')]
    public function brandModels(string $brand, BrandRepository $brandRep): JsonResponse
    {
        if ($brand == null)
            return new JsonResponse([
                'message' => 'Invalid request data (brand must be stringable)',
            ], Response::HTTP_BAD_REQUEST);

        $models = [];
        $brandEntities = $brandRep->findBy(['brand' => $brand]);

        foreach ($brandEntities as $brandEntity) {
            if (!in_array($brandEntity->getModel(), $models))
                $models[] = $brandEntity->getModel();
        }

        return new JsonResponse($models, Response::HTTP_OK);
    }

    /**
     * @throws \Exception
     */
    #[Route('/ajax/categories', name: 'details_list_categories')]
    public function listCategories(Request $req): Response
    {
        if (!$req->query->has('catalog') ||
            !$req->query->has('vehicle_id') ||
            !$req->query->has('vehicle_ssd') ||
            !$req->query->has('group_id'))
        {
            return new JsonResponse([
                'message' => 'invalid request'
            ]);
        }

        $categories = $this->serviceOem->listQuickDetail($req->query->get('catalog'),
            $req->query->get('vehicle_id'),
            $req->query->get('vehicle_ssd'),
            $req->query->get('group_id'))->getCategories();

        $unitImageMaps = [];
        foreach ($categories as $category) {
            foreach ($category->getUnits() as $unit) {
                $unitImageMap = $this->serviceOem->listImageMapByUnit($req->query->get('catalog'), $unit->getSsd(), $unit->getUnitId());
                if (array_key_exists($unit->getUnitId(), $unitImageMaps))
                    throw new \Exception('В $unitImageMaps уже есть элемент с ключом '.$unit->getUnitId());

                $unitImageMaps[$unit->getUnitId()] = $unitImageMap;
            }
        }

        return $this->render('details/categories-list.html.twig', [
            'categories' => $categories,
            'unit_image_maps' => $unitImageMaps
        ]);
    }

    #[Route('/ajax/details', name: 'details_list_details')]
    public function listDetails(Request $req, AbcpApi $abcpApi): Response
    {
        $oems = explode(',', json_decode($req->getContent(), true)['oems'] ?? '');
        if (empty($oems)) {
            return new JsonResponse([
                'message' => 'Invalid request data',
                'valid data example' => '{"oems":"1125406206B,1420608250B,1471175006B"}'
            ]);
        }

        $abcpArticles = $abcpApi->searchProcessor->searchBatchArticlesByNumbers($oems);

        return $this->render('details/details-list.html.twig', [
            'products' => $abcpArticles,
            'descriptionArrayIndexes' => (new DataMapping())->getData('position_description_array_indexes')
        ]);
    }
}

templates/details/categories-list.html.twig
{% for category in categories %}
    {% for unit in category.units %}
        {% include 'pieces/unit_card.html.twig' with { 'unit': unit, 'unit_image_maps': unit_image_maps } %}
    {% endfor %}
{% endfor %}

templates/details/detail_info.html.twig
{% set productDescriptionArray = product['description']|split(';') %}
{% set productName = productDescriptionArray[descriptionArrayIndexes['name']] %}
{% set productImageLink = productDescriptionArray[descriptionArrayIndexes['img_link']] %}
{% set productImageWeight = productDescriptionArray[descriptionArrayIndexes['weight']] %}
{% set productImageLength = productDescriptionArray[descriptionArrayIndexes['length']] %}
{% set productImageWidth = productDescriptionArray[descriptionArrayIndexes['width']] %}
{% set productImageHeight = productDescriptionArray[descriptionArrayIndexes['height']] %}
{% set productAdditionalImgLinks = productDescriptionArray[descriptionArrayIndexes['additional_img_links']]|replace({' ': ''})|split(',') %}

<div class="detail-full-info" data-detail-id="{{ product['itemKey'] }}">
    <h5 class="detail-full-info__name" style="font-weight: 300">{{ productName }}</h5>
    <div class="detail-full-info__content">
        <div class="detail-full-info__left">
            <div class="detail-full-info__img-wrapper">
                <img src="{{ productImageLink }}" alt="{{ productName }}" class="img-thumbnail detail-full-info__img">
            </div>
            <div class="detail-full-info__gallery">
                {% set productImageLinks = productAdditionalImgLinks %}
                {% for imageLink in productImageLinks %}
                    {% if imageLink != '' %}
                        <div class="detail-full-info__gallery-item js-put-to-image-wrapper">
                            <img src="{{ imageLink }}">
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="detail-full-info__right">
            <div class="detail-full-info__info">
                <p class="info-row">
                    <span>Производитель</span>
                    <span>{{ product['brand'] }}</span>
                </p>
                <p class="info-row">
                    <span>Артикул</span>
                    <span>{{ product['number'] }}</span>
                </p>
                <p class="detail-full-info__total-balance info-row">
                    <span>В наличии</span>
                    <span>{{ product['availability'] }}шт</span>
                </p>
                <p class="detail-full-info__price info-row">
                    <span style="color: red !important;">Цена</span>
                    <span>{{ product['price'] }} ₽</span>
                </p>
                <br>
                <p class="info-row">
                    <span>Длина</span>
                    <span>{{ productImageLength }}</span>
                </p>
                <p class="info-row">
                    <span>Ширина</span>
                    <span>{{ productImageWidth }}</span>
                </p>
                <p class="info-row">
                    <span>Высота</span>
                    <span>{{ productImageHeight }}</span>
                </p>
                <p class="info-row">
                    <span>Вес</span>
                    <span>{{ productImageWeight }}</span>
                </p>
            </div>
        </div>
    </div>
</div>

templates/details/detail_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.name }}{% endblock %}

{% block body %}
    <div class="detail-full-info" data-detail-id="{{ product.id }}" style="width: 100%;padding-top: 1rem;">
        <h4 class="detail-full-info__name">{{ product.name }}</h4>
        <div class="detail-full-info__content">
            <div class="detail-full-info__left">
                <div class="detail-full-info__img-wrapper">
                    <img src="{{ product.imageLink }}" alt="{{ product.name }}" class="img-thumbnail detail-full-info__img">
                </div>
            </div>
            <div class="detail-full-info__right">
                <div class="detail-full-info__info">
                    <p class="info-row">
                        <span>Производитель</span>
                        <span>{{ product.brand }}</span>
                    </p>
                    <p class="info-row">
                        <span>Артикул</span>
                        <span>{{ product.articleNumber }}</span>
                    </p>
                    <p class="detail-full-info__total-balance info-row">
                        <span>В наличии</span>
                        <span>{{ product.totalBalance }}{{ product.measurementUnit }}</span>
                    </p>
                    <p class="detail-full-info__price info-row">
                        <span style="color: red !important;">Цена</span>
                        <span>{{ product.price }} ₽</span>
                    </p>
                </div>
                <div class="detail-full-info__cart-buttons">
                    {% if in_cart_quantity > 0 %}
                        <div class="detail-full-info__quantity-counter">
                            <span class="detail-full-info__minus-btn js-decrease-cart-item">-</span>
                            <span class="detail-full-info__amount">{{ in_cart_quantity }}</span>
                            <span class="detail-full-info__plus-btn js-add-to-cart">+</span>
                        </div>
                    {% else %}
                        <button type="button" class="btn btn-dark js-add-to-cart">В корзину</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/details/details-list.html.twig
{% for product in products %}
    {% include 'pieces/product_card.html.twig' with { 'product': product, 'descriptionArrayIndexes': descriptionArrayIndexes } %}
{% endfor %}