src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'parent_order', targetEntity: CartItem::class)]
    private Collection $items;

    #[ORM\Column(length: 20)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $customer = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?int $payment_type = null;

    #[ORM\Column(length: 50)]
    private ?int $status = null;

    #[ORM\Column(length: 255)]
    private ?string $client_fullname = null;

    #[ORM\Column(length: 55)]
    private ?int $way_to_get = null;

    #[ORM\OneToMany(mappedBy: 'updated_order', targetEntity: Notification::class)]
    private Collection $notifications;

    #[ORM\OneToMany(mappedBy: 'parentOrder', targetEntity: OrderComment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $delivery_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $alfabank_order_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $alfabank_payment_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_geocoords = null;

    #[ORM\Column]
    #[Assert\Choice(choices: [-1, 0, 1])]
    private ?int $payment_status = null;

    #[ORM\Column(nullable: true)]
    private ?int $abcpOrderNumber = null;

    #[Pure]
    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(CartItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setParentOrder($this);
        }

        return $this;
    }

    public function removeItem(CartItem $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getParentOrder() === $this) {
                $item->setParentOrder(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCustomer(): ?User
    {
        return $this->customer;
    }

    public function setCustomer(?User $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getPaymentType(): ?int
    {
        return $this->payment_type;
    }

    public function setPaymentType(int $payment_type): self
    {
        $this->payment_type = $payment_type;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getClientFullname(): ?string
    {
        return $this->client_fullname;
    }

    public function setClientFullname(string $client_fullname): self
    {
        $this->client_fullname = $client_fullname;

        return $this;
    }

    public function getWayToGet(): ?int
    {
        return $this->way_to_get;
    }

    public function setWayToGet(int $way_to_get): self
    {
        $this->way_to_get = $way_to_get;

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setUpdatedOrder($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getUpdatedOrder() === $this) {
                $notification->setUpdatedOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderComment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(OrderComment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setParentOrder($this);
        }

        return $this;
    }

    public function removeComment(OrderComment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getParentOrder() === $this) {
                $comment->setParentOrder(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDeliveryType(): ?int
    {
        return $this->delivery_type;
    }

    public function setDeliveryType(?int $delivery_type): self
    {
        $this->delivery_type = $delivery_type;

        return $this;
    }

    public function getAlfabankOrderId(): ?string
    {
        return $this->alfabank_order_id;
    }

    public function setAlfabankOrderId(?string $alfabank_order_id): self
    {
        $this->alfabank_order_id = $alfabank_order_id;

        return $this;
    }

    public function getAlfabankPaymentUrl(): ?string
    {
        return $this->alfabank_payment_url;
    }

    public function setAlfabankPaymentUrl(?string $alfabank_payment_url): self
    {
        $this->alfabank_payment_url = $alfabank_payment_url;

        return $this;
    }

    public function getAddressGeocoords(): ?string
    {
        return $this->address_geocoords;
    }

    public function setAddressGeocoords(?string $address_geocoords): self
    {
        $this->address_geocoords = $address_geocoords;

        return $this;
    }

    public function getPaymentStatus(): ?int
    {
        return $this->payment_status;
    }

    public function setPaymentStatus(int $payment_status): self
    {
        $this->payment_status = $payment_status;

        return $this;
    }

    public function getAbcpOrderNumber(): ?int
    {
        return $this->abcpOrderNumber;
    }

    public function setAbcpOrderNumber(int $abcpOrderNumber): self
    {
        $this->abcpOrderNumber = $abcpOrderNumber;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\AbcpOrderCustomFieldsEntityRepository;
use App\Service\ThirdParty\Abcp\AbcpApi;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/order')]
class OrderController extends AbstractController
{
    #[Route('/item/{id}', name: 'order_page')]
    #[IsGranted('ROLE_USER')]
    public function show($id, AbcpApi $abcpApi, Request $req, AbcpOrderCustomFieldsEntityRepository $abcpOrderCustomFieldsEntityRep): Response
    {
        if (!is_numeric($id))
            return $this->redirectToRoute('homepage');

        /** @var User $user */
        $user = $this->getUser();
        $order = $abcpApi->basketProcessor->getOrderByNumber($user, $id);
        $orderCustomFieldsEntity = $abcpOrderCustomFieldsEntityRep->findOneBy(['abcpOrderNumber' => $id]);
        $paymentResult = $req->query->get('payment_result');

        if ($paymentResult === 'success' && !$orderCustomFieldsEntity->isIsPaid()) {
            $orderSum = (float) str_replace(' ', '', $order['sum']);
            $abcpApi->cpProcessor->commitPaymentToOrder($user, 27840, $orderSum, $order['number']);
            
            $orderCustomFieldsEntity->setIsPaid(true);
            $abcpOrderCustomFieldsEntityRep->save($orderCustomFieldsEntity, true);
            $this->addFlash('success', 'Оплата прошла успешно');

            return $this->redirectToRoute('order_page', ['id' => $id]);
        }
        elseif($paymentResult === 'fail') {
            $this->addFlash('danger', 'Платеж отклонен');
            return $this->redirectToRoute('order_page', ['id' => $id]);
        }

        return $this->render('order/show.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/my_orders', name: 'order_my_orders')]
    #[IsGranted('ROLE_USER')]
    public function index(Request $req, AbcpApi $abcpApi): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $ordersSkip = $req->get('ordersSkip', 0);
        $ordersLimit = $req->get('ordersLimit', 100);

        $orders = $abcpApi->orderProcessor->getUserOrders($user, $ordersSkip, $ordersLimit)['items'];
        return $this->render('order/index.html.twig', [
            'orders' => $orders,
        ]);
    }
}

templates/order/create_form.twig
<div class="order-form-container">
    <h3>Оформление заказа</h3>
    <p>Выделите товары сверху, заполните форму и нажмите на "Оформить заказ"</p>
    {{ form_start(order_form) }}

    {% block choice_way_to_get_widget %}
        <div style="margin-bottom: 1rem;" class="way_to_get">
            <strong>Способ получения</strong>
            <div id="way_to_get_inputs" style="margin-top: .5rem">
                {% for radio_child in order_form.way_to_get %}
                    {{ form_widget(radio_child, {'attr': {'class': 'form-check-input'}}) }}
                    {{ form_label(radio_child, null, {'label_attr' : {'class': 'text-muted'}}) }}
                {% endfor %}
            </div>
        </div>
    {% endblock %}
    {% block choice_delivery_type_widget %}
        <div style="margin-bottom: 1rem;" class="delivery_type waytoget-state-item rfdelivery-state-item">
            <strong>Способ доставки</strong>
            <div id="delivery_type_inputs" style="margin-top: .5rem">
                {% for radio_child in order_form.delivery_type %}
                    {{ form_widget(radio_child, {'attr': {'class': 'form-check-input'}}) }}
                    {{ form_label(radio_child, null, {'label_attr' : {'class': 'text-muted'}}) }}
                {% endfor %}
            </div>
        </div>
    {% endblock %}
    {{ form_row(order_form.city) }}
    {{ form_row(order_form.address) }}
    {{ form_row(order_form.addressGeocoords) }}
    {% block choice_payment_type_widget %}
        <div style="margin-bottom: 1rem; margin-top: 1rem;" id="create_order_form_payment_type">
            <strong>Способ оплаты:</strong>
            {% for radio_child in order_form.payment_type %}
                <div class="payment-type-input {% if not loop.first %}waytoget-state-item pickup-state-item{% endif %}">
                    {{ form_widget(radio_child, {'attr': {'class': 'form-check-input'}}) }}
                    {{ form_label(radio_child, null, {'label_attr' : {'class': 'text-muted'}}) }}
                </div>
            {% endfor %}
        </div>
    {% endblock %}

    <input type="hidden" id="cart_items_ids" name="cart_items_ids" value="">
    <div class="order-form__buttons">
        <button type="submit" class="btn btn-dark">Оформить заказ</button>
        <div class="waytoget-state-item rfdelivery-state-item dellin-calculation-buttons">
            <button type="button" class="btn btn-success btn-sm js-calculate-shipping-cost">Расчитать примерную
                стоимость доставки
            </button>
            <button type="button" class="btn btn-primary btn-sm js-show-calculation-modal"
                    title="Калькулятор стоимости доставки"><i
                        class="fa-solid fa-calculator js-show-calculation-modal"></i></button>
            <span class="calculate-btn-tip" title="Оплата доставки по РФ проводится по получению товара">?</span>
        </div>
    </div>
    {{ form_end(order_form) }}
</div>

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Мои заказы{% endblock %}

{% block body %}
    {% if orders|length > 0 %}
        <div id="orders">
            {% for order in orders %}
                {% include 'pieces/order_card.html.twig' with { 'order': order } %}
            {% endfor %}
        </div>
    {% else %}
        <div class="empty-cart-message-wrapper">
            <h5 style="width: 150px; text-align: center">
                Вашей машине грустно, когда тут пусто :(
            </h5>
        </div>
    {% endif %}
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Заказ № {{ order['number'] }}{% endblock %}

{% block body %}
    {{ include('@EasyAdmin/flash_messages.html.twig') }}
    <h5>Итоговая сумма: {{ order['sum'] }}<span class="small">₽</span></h5>
    <br>

    <div class="order-table">
        <div class="order-row">
            <div class="order-label text-muted">
                Номер заказа
            </div>
            <div class="order-value order-id">
                {{ order['number'] }}
            </div>
        </div>
        <div class="order-row">
            <div class="order-label text-muted">
                Дата заказа
            </div>
            <div class="order-value">
                {{ order['date'] }}
            </div>
        </div>
        <div class="order-row">
            <div class="order-label text-muted">
                Статус заказа
            </div>
            <div class="order-value">
                {{ order['status'] }}
            </div>
        </div>
        <div class="order-row">
            {% if 'deliveryAddress' in order and order['deliveryAddress'] is defined %}
                <div class="order-label text-muted">
                    Адрес
                </div>
                <div class="order-value">
                    {{ order['deliveryAddress'] }}
                </div>
            {% endif %}
        </div>
        <div class="order-row">
            <div class="order-label text-muted">
                Товары
            </div>
            <div class="order-value">
                <a href="#" class="js-toggle-order-products-visibility">Показать товары</a>
                <br>
                <br>
                {% for item in order['positions'] %}
                    <div class="order-product hidden">
                        <p><a href="{{ path('detail_info', {'articleNumber': item['number'], 'itemKey': item['itemKey']}) }}" class="product-link">{{ item['description'] }}</a></p>
                        <p>{{ item['quantity'] }}<span class="small">шт</span> - {{ item['price'] }}<span class="small">₽</span></p>
                        {% if not loop.last %}
                            <hr>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {#  Тут был блок с комментариями  #}
{% endblock %}